#!/usr/bin/env python3
"""Apply the verified Google Sheet artist rows 150 through 176."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
UPDATES_FILE = ROOT / "config" / "verified-artist-registry-updates.json"
IMAGE_OVERRIDES_FILE = ROOT / "config" / "verified-artist-image-overrides.json"


SPOTIFY_IMAGE_URLS = {
    "1WlJORCWCG2F0TBI4sReri": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5ebf1a7e4abb6ee247fd2c04de5",
    "24p0hSTqoxNsy89rKNrSDj": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5eb9fa4da984eb788edaa3839ad",
    "6jwSYdglftKLb8vhvAfNag": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5ebb554962c100087e71d7b4104",
    "2zcu7rparMOCBU7ZaBMb4N": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb087c4b1a01232a29fb75de1e",
    "2jsFUZcvMqEU9ay3BWHgAg": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb04309a0ad05ff113a5b80231",
    "3iJk6wDUly0uF53bdlBfvT": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb0550a8d0f743c40ac59162f3",
    "2KuGCEmfjdATgtfBlmFMxS": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5ebe1c7145787a2c2cd997de7c4",
    "0WI8OfWCRvK4nGHmKfFQmd": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb2c81bb40c3b6962eacf9dc9c",
    "0sHeKC0Zcxpz4wOHHE5oJ7": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb603501102ca962a0b333228f",
    "5bLqm0pB0l0J5hRMXajA0S": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5eb5ba06e67f0abf5349a782d45",
    "1Jrih9sEoE7aI00lQ6dciO": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5ebc50cebd2c2f5d86260e69e9f",
    "4WGlZzRh7PszMcCdPV80tj": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5eb91fd7ecda2a257e8f0b5168f",
    "3EcMKVigl7YMEeDmWGcezy": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb16f2f80d2e01df2baa0c479b",
    "62xS59NTx0ruEKAvlQshqB": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb57c526b89fa2185fc665f825",
    "3S5xX5qyLz6rHm9iobW1jS": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5eb46667ac884ef90dd59b54434",
    "2UVyRB0Sb8BJQeuK3lmziU": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb45dfa91b2fbe804937ed457d",
    "0dwtjZ8Egrjgf2Nf9DlaZk": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb40930244e031d23a5badecda",
    "47fuPz0K0cyruPcpXiBo2W": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5eb257bcb7b1666859c95bdcb04",
    "46UmMAKrHKTvwKAV5mrNsi": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb4478ed7a506218d9637c7764",
    "6qDQ0Rnp9bj86ZcsI4UkEX": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb1d1cb63cad9990a767c54748",
    "6qE9NgK1b0kDnGUnGVh4zS": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5ebc2a6e932ece80c11a69d6faf",
    "5G1xrscxyvpYHX72E108iW": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb43049c6b48d193bfb558ca53",
    "0e6JPJ634Hw3I95aKMEaD7": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5eb37fd42025d87f65426aa45b0",
    "1EswPCHgI3tydeJlDVMEFl": "https://image-cdn-ak.spotifycdn.com/image/ab6761610000e5eb5895eca28adaccc304472663",
    "0gqbW7Uf6BAWiAh5C6jlPs": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5ebed75a5a3ab0bd75a23bffb16",
    "419NjKezGEJOVPtiymCp2p": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb32042962fc801509158784db",
    "65qv2AiHO3xVWAs4SCKx4O": "https://image-cdn-fa.spotifycdn.com/image/ab6761610000e5eb1c3e7f011b0fb755fd707492",
}


def spotify_image(spotify_id: str) -> str:
    return SPOTIFY_IMAGE_URLS[spotify_id]


ROWS = [
    {
        "rosterOrder": 150,
        "name": "C4 Crotona",
        "aliases": ["C4 Crotona"],
        "category": "core",
        "monitoringPriority": 1,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.themenacemovement.com/c4-crotona/",
        "instagramProfile": "https://www.instagram.com/c4crotona_/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/1WlJORCWCG2F0TBI4sReri",
        "youtubeProfile": "https://www.youtube.com/@C4Crotona",
        "officialImageSource": "https://www.themenacemovement.com/c4-crotona/",
        "imageUrl": spotify_image("1WlJORCWCG2F0TBI4sReri"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 151,
        "name": "Nathan Davis Jr.",
        "aliases": ["Nathan Davis Jr.", "Nathan Davis Jr"],
        "category": "crossover",
        "monitoringPriority": 2,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://www.iamndj.com/",
        "instagramProfile": "https://www.instagram.com/nathandavisjrndj",
        "spotifyProfile": "https://open.spotify.com/artist/24p0hSTqoxNsy89rKNrSDj",
        "youtubeProfile": "https://www.youtube.com/c/NathanDavisJr",
        "officialImageSource": "https://www.iamndj.com/",
        "imageUrl": spotify_image("24p0hSTqoxNsy89rKNrSDj"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 152,
        "name": "MAYIA",
        "aliases": ["MAYIA", "Mayia"],
        "category": "core",
        "monitoringPriority": 2,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/mayiawarren/?hl=en",
        "instagramProfile": "https://www.instagram.com/mayiawarren/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/6jwSYdglftKLb8vhvAfNag",
        "youtubeProfile": "https://www.youtube.com/@OFFICIALMAYIAWARREN",
        "officialImageSource": "https://www.instagram.com/mayiawarren/?hl=en",
        "imageUrl": spotify_image("6jwSYdglftKLb8vhvAfNag"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 153,
        "name": "Trendsetter Sense",
        "aliases": ["Trendsetter Sense"],
        "category": "rmg",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": True,
        "website": "https://www.instagram.com/trendsettersense/?hl=en",
        "instagramProfile": "https://www.instagram.com/trendsettersense/",
        "spotifyProfile": "https://open.spotify.com/artist/2zcu7rparMOCBU7ZaBMb4N",
        "youtubeProfile": "https://www.youtube.com/@TrendsetterSense/about",
        "officialImageSource": "https://www.instagram.com/trendsettersense/?hl=en",
        "imageUrl": spotify_image("2zcu7rparMOCBU7ZaBMb4N"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 154,
        "name": "Monster Tarver",
        "aliases": ["Monster Tarver", "Tyrone Evans"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://www.themenacemovement.com/monster-tarver/",
        "instagramProfile": "https://www.instagram.com/monstertarver/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/2jsFUZcvMqEU9ay3BWHgAg",
        "youtubeProfile": "https://www.youtube.com/channel/UC8sHqu7bM_zfOK1dazpcOBw",
        "officialImageSource": "https://www.themenacemovement.com/monster-tarver/",
        "imageUrl": spotify_image("2jsFUZcvMqEU9ay3BWHgAg"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 155,
        "name": "Lul DreDay",
        "aliases": ["Lul DreDay", "Lul Dreday"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": True,
        "website": "https://www.instagram.com/luldreday/?hl=en",
        "instagramProfile": "https://www.instagram.com/luldreday/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/3iJk6wDUly0uF53bdlBfvT",
        "youtubeProfile": "https://www.youtube.com/channel/UC8Oiej_PXzv88c_M33KjBJg",
        "officialImageSource": "https://www.instagram.com/luldreday/?hl=en",
        "imageUrl": spotify_image("3iJk6wDUly0uF53bdlBfvT"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 156,
        "name": "Brinson",
        "aliases": ["Brinson"],
        "category": "legacy",
        "monitoringPriority": 3,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://godchaserz.com/",
        "instagramProfile": "https://www.instagram.com/godchaserz/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/2KuGCEmfjdATgtfBlmFMxS",
        "youtubeProfile": "https://www.youtube.com/user/BrinsonVEVO",
        "officialImageSource": "https://godchaserz.com/",
        "imageUrl": spotify_image("2KuGCEmfjdATgtfBlmFMxS"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 157,
        "name": "Alex Zurdo",
        "aliases": ["Alex Zurdo"],
        "category": "international",
        "monitoringPriority": 3,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://www.alexzurdomusic.com/site/",
        "instagramProfile": "https://www.instagram.com/alexzurdomusic/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/0WI8OfWCRvK4nGHmKfFQmd",
        "youtubeProfile": "https://www.youtube.com/user/ALEXZURDOMUSIC",
        "officialImageSource": "https://www.alexzurdomusic.com/site/",
        "imageUrl": spotify_image("0WI8OfWCRvK4nGHmKfFQmd"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 158,
        "name": "Jay Kalyl",
        "aliases": ["Jay Kalyl"],
        "category": "international",
        "monitoringPriority": 3,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://www.instagram.com/jaykalylmusic/?hl=en",
        "instagramProfile": "https://www.instagram.com/jaykalyl/",
        "spotifyProfile": "https://open.spotify.com/artist/0sHeKC0Zcxpz4wOHHE5oJ7",
        "youtubeProfile": "https://www.youtube.com/channel/UCFfyV-7bdXPRDZfItdZdpQg",
        "officialImageSource": "https://www.instagram.com/jaykalylmusic/?hl=en",
        "imageUrl": spotify_image("0sHeKC0Zcxpz4wOHHE5oJ7"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 159,
        "name": "Key'ijah",
        "aliases": ["Key'ijah"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/iamkeyijah/?hl=en",
        "instagramProfile": "https://www.instagram.com/iamkeyijah/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/5bLqm0pB0l0J5hRMXajA0S",
        "youtubeProfile": "https://www.youtube.com/@Official_Keyijah",
        "officialImageSource": "https://www.instagram.com/iamkeyijah/?hl=en",
        "imageUrl": spotify_image("5bLqm0pB0l0J5hRMXajA0S"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 160,
        "name": "Tha inspiration",
        "aliases": ["Tha inspiration"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/tha.inspirati0n/",
        "instagramProfile": "https://www.instagram.com/tha.inspirati0n/",
        "spotifyProfile": "https://open.spotify.com/artist/1Jrih9sEoE7aI00lQ6dciO",
        "youtubeProfile": "https://www.youtube.com/@Thainspiration",
        "officialImageSource": "https://www.instagram.com/tha.inspirati0n/",
        "imageUrl": spotify_image("1Jrih9sEoE7aI00lQ6dciO"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 161,
        "name": "NISSI SHALOM",
        "aliases": ["NISSI SHALOM"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/itsnissishalom/",
        "instagramProfile": "https://www.instagram.com/itsnissishalom/",
        "spotifyProfile": "https://open.spotify.com/artist/4WGlZzRh7PszMcCdPV80tj",
        "youtubeProfile": "https://www.youtube.com/@RighteousTM633",
        "officialImageSource": "https://www.instagram.com/itsnissishalom/",
        "imageUrl": spotify_image("4WGlZzRh7PszMcCdPV80tj"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 162,
        "name": "SteveUnordinary",
        "aliases": ["SteveUnordinary"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/steveunordinary/?hl=en",
        "instagramProfile": "https://www.instagram.com/steveunordinary/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/3EcMKVigl7YMEeDmWGcezy",
        "youtubeProfile": "https://www.youtube.com/c/SteveOrdinary/videos",
        "officialImageSource": "https://www.instagram.com/steveunordinary/?hl=en",
        "imageUrl": spotify_image("3EcMKVigl7YMEeDmWGcezy"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 163,
        "name": "JJ Chosen",
        "aliases": ["JJ Chosen"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/jjchosenofficial/",
        "instagramProfile": "https://www.instagram.com/jjchosenofficial/",
        "spotifyProfile": "https://open.spotify.com/artist/62xS59NTx0ruEKAvlQshqB",
        "youtubeProfile": "https://www.youtube.com/channel/UCqTS2tmNKlvu8YNbX_7vGuQ",
        "officialImageSource": "https://www.instagram.com/jjchosenofficial/",
        "imageUrl": spotify_image("62xS59NTx0ruEKAvlQshqB"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 164,
        "name": "Generation Recovery",
        "aliases": ["Generation Recovery"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/generationrecoverymusic/?hl=en",
        "instagramProfile": "https://www.instagram.com/generationrecoverymusic/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/3S5xX5qyLz6rHm9iobW1jS",
        "youtubeProfile": "",
        "officialImageSource": "https://www.instagram.com/generationrecoverymusic/?hl=en",
        "imageUrl": spotify_image("3S5xX5qyLz6rHm9iobW1jS"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 165,
        "name": "IFearGod",
        "aliases": ["IFearGod"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/ifeargod3/",
        "instagramProfile": "https://www.instagram.com/ifeargod3/",
        "spotifyProfile": "https://open.spotify.com/artist/2UVyRB0Sb8BJQeuK3lmziU",
        "youtubeProfile": "https://www.youtube.com/channel/UC0WGs4a9ylf2cIlefObDZKw",
        "officialImageSource": "https://www.instagram.com/ifeargod3/",
        "imageUrl": spotify_image("2UVyRB0Sb8BJQeuK3lmziU"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 166,
        "name": "Hy Chu",
        "aliases": ["Hy Chu"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/therealhychu/",
        "instagramProfile": "https://www.instagram.com/therealhychu/",
        "spotifyProfile": "https://open.spotify.com/artist/0dwtjZ8Egrjgf2Nf9DlaZk",
        "youtubeProfile": "https://www.youtube.com/channel/UC0GMYFL2ubouuGSxnmBTg8Q",
        "officialImageSource": "https://www.instagram.com/therealhychu/",
        "imageUrl": spotify_image("0dwtjZ8Egrjgf2Nf9DlaZk"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 167,
        "name": "Vennisay",
        "aliases": ["Vennisay"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/vennisay/?hl=en",
        "instagramProfile": "https://www.instagram.com/vennisay/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/47fuPz0K0cyruPcpXiBo2W",
        "youtubeProfile": "https://www.youtube.com/channel/UCRi6WTcaC__0ZWq_d2xJ_qw",
        "officialImageSource": "https://www.instagram.com/vennisay/?hl=en",
        "imageUrl": spotify_image("47fuPz0K0cyruPcpXiBo2W"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 168,
        "name": "Scarlito Jr.",
        "aliases": ["Scarlito Jr.", "Scarlito Jr"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/scarlitojr/",
        "instagramProfile": "https://www.instagram.com/scarlitojr/",
        "spotifyProfile": "https://open.spotify.com/artist/46UmMAKrHKTvwKAV5mrNsi",
        "youtubeProfile": "https://music.youtube.com/channel/UCSt6mc5-My-19YkXmMKhgFw",
        "officialImageSource": "https://www.instagram.com/scarlitojr/",
        "imageUrl": spotify_image("46UmMAKrHKTvwKAV5mrNsi"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 169,
        "name": "J Reborn",
        "aliases": ["J Reborn"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/jreborn_official/",
        "instagramProfile": "https://www.instagram.com/jreborn_official/",
        "spotifyProfile": "https://open.spotify.com/artist/6qDQ0Rnp9bj86ZcsI4UkEX",
        "youtubeProfile": "https://www.youtube.com/channel/UCa2iewWs6MlV092uo0zulfQ",
        "officialImageSource": "https://www.instagram.com/jreborn_official/",
        "imageUrl": spotify_image("6qDQ0Rnp9bj86ZcsI4UkEX"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 170,
        "name": "Dre Skywalker",
        "aliases": ["Dre Skywalker"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/dreskywalkerofficial/",
        "instagramProfile": "https://www.instagram.com/dreskywalkerofficial/",
        "spotifyProfile": "https://open.spotify.com/artist/6qE9NgK1b0kDnGUnGVh4zS",
        "youtubeProfile": "https://www.youtube.com/@Dre.Skywalker",
        "officialImageSource": "https://www.instagram.com/dreskywalkerofficial/",
        "imageUrl": spotify_image("6qE9NgK1b0kDnGUnGVh4zS"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 171,
        "name": "Gabriel Katon",
        "aliases": ["Gabriel Katon"],
        "category": "core",
        "monitoringPriority": 3,
        "ticketmasterEnabled": False,
        "textMatchEnabled": False,
        "website": "https://www.instagram.com/gabriel.katon/",
        "instagramProfile": "https://www.instagram.com/gabriel.katon/",
        "spotifyProfile": "https://open.spotify.com/artist/5G1xrscxyvpYHX72E108iW",
        "youtubeProfile": "https://www.youtube.com/channel/UCytJ0RS91XUJf4wYrmt3prQ",
        "officialImageSource": "https://www.instagram.com/gabriel.katon/",
        "imageUrl": spotify_image("5G1xrscxyvpYHX72E108iW"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 172,
        "name": "Red Tips",
        "aliases": ["Red Tips"],
        "category": "core",
        "monitoringPriority": 1,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://redtips.world/",
        "instagramProfile": "https://www.instagram.com/redtips.music/",
        "spotifyProfile": "https://open.spotify.com/artist/0e6JPJ634Hw3I95aKMEaD7",
        "youtubeProfile": "https://www.youtube.com/channel/UC1q_9w95T3eprZwAFTXyrUg",
        "officialImageSource": "https://www.instagram.com/redtips.music/",
        "imageUrl": spotify_image("0e6JPJ634Hw3I95aKMEaD7"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 173,
        "name": "Dell Mac",
        "aliases": ["Dell Mac"],
        "category": "core",
        "monitoringPriority": 1,
        "ticketmasterEnabled": False,
        "textMatchEnabled": True,
        "website": "https://www.instagram.com/dellmac301/?hl=en",
        "instagramProfile": "https://www.instagram.com/dellmac301/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/1EswPCHgI3tydeJlDVMEFl",
        "youtubeProfile": "https://www.youtube.com/channel/UClRb8RvKMxpM7rFlsd6P8RQ",
        "officialImageSource": "https://www.instagram.com/dellmac301/?hl=en",
        "imageUrl": spotify_image("1EswPCHgI3tydeJlDVMEFl"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 174,
        "name": "Tommy Royale",
        "aliases": ["Tommy Royale"],
        "category": "core",
        "monitoringPriority": 1,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://www.instagram.com/iamtommyroyale/?hl=en",
        "instagramProfile": "https://www.instagram.com/iamtommyroyale/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/0gqbW7Uf6BAWiAh5C6jlPs?go=1&sp_cid=67e19d32c5200acbd7c434127ccd2bbe",
        "youtubeProfile": "https://music.youtube.com/channel/UC3CXVdZvDlK4HZtyuav26LQ",
        "officialImageSource": "https://www.instagram.com/iamtommyroyale/?hl=en",
        "imageUrl": spotify_image("0gqbW7Uf6BAWiAh5C6jlPs"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 175,
        "name": "Ty Brasel",
        "aliases": ["Ty Brasel"],
        "category": "core",
        "monitoringPriority": 1,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://youngtyman.com/",
        "instagramProfile": "https://www.instagram.com/Ty_Brasel",
        "spotifyProfile": "https://open.spotify.com/artist/419NjKezGEJOVPtiymCp2p",
        "youtubeProfile": "https://www.youtube.com/c/TyBrasel/about",
        "officialImageSource": "https://www.instagram.com/Ty_Brasel",
        "imageUrl": spotify_image("419NjKezGEJOVPtiymCp2p"),
        "imagePosition": "center",
    },
    {
        "rosterOrder": 176,
        "name": "J. Monty",
        "aliases": ["J. Monty", "J Monty"],
        "category": "core",
        "monitoringPriority": 1,
        "ticketmasterEnabled": True,
        "textMatchEnabled": True,
        "website": "https://www.instagram.com/jmontystudios/?hl=en",
        "instagramProfile": "https://www.instagram.com/jmontystudios/?hl=en",
        "spotifyProfile": "https://open.spotify.com/artist/65qv2AiHO3xVWAs4SCKx4O",
        "youtubeProfile": "https://www.youtube.com/@JMontystudios",
        "officialImageSource": "https://www.instagram.com/jmontystudios/?hl=en",
        "imageUrl": spotify_image("65qv2AiHO3xVWAs4SCKx4O"),
        "imagePosition": "center",
    },
]


def main() -> int:
    updates = json.loads(UPDATES_FILE.read_text(encoding="utf-8"))
    replacement_names = {row["name"].casefold() for row in ROWS}
    updates = [
        row for row in updates
        if str(row.get("name") or "").casefold() not in replacement_names
    ]
    updates.extend(ROWS)
    updates.sort(key=lambda row: int(row["rosterOrder"]))
    UPDATES_FILE.write_text(
        json.dumps(updates, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    image_overrides = json.loads(IMAGE_OVERRIDES_FILE.read_text(encoding="utf-8"))
    image_overrides.update({row["name"]: row["imageUrl"] for row in ROWS})
    IMAGE_OVERRIDES_FILE.write_text(
        json.dumps(image_overrides, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Applied {len(ROWS)} verified artist registry rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
